### ISSUE TITLE
Validação de parâmetros casos de uso

### ISSUE THREAD

**Issue by bmviniciuss** [bmviniciuss/lab-mps#3]
A validação do usuário, ou outros parâmetros dos casos de uso, iremos deixar no `UserController`?
Podemos criar uma interface e usaremos em cada caso de uso e criamos uma classe que implemente a interface com as regras lá. Ou alguém tem alguma sugestão de como fazer, ou se devemos deixar da forma como está atualmente?

**Comment by AgtHrq** [comment]
Para essa primeira entrega deixamos da forma que está atualmente, mas é algo que se deve considerar para versões futuras.
